# Generated by Django 5.0.6 on 2024-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subject_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Teacher'), (2, 'Chief-Teacher'), (3, 'Student')], default=3),
        ),
    ]
