# Generated by Django 5.0.6 on 2024-06-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_managers_remove_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
